all: ../$(OBJ_DIR)/op_engine/canvas.o \
../$(OBJ_DIR)/op_engine/collide_box.o \
../$(OBJ_DIR)/op_engine/input.o \
../$(OBJ_DIR)/op_engine/line.o \
../$(OBJ_DIR)/op_engine/matrix.o \
../$(OBJ_DIR)/op_engine/mesh.o \
../$(OBJ_DIR)/op_engine/object.o \
../$(OBJ_DIR)/op_engine/plane.o \
../$(OBJ_DIR)/op_engine/segment.o \
../$(OBJ_DIR)/op_engine/transform.o \
../$(OBJ_DIR)/op_engine/triangle.o \
../$(OBJ_DIR)/op_engine/vector.o \

../$(OBJ_DIR)/op_engine/canvas.o : canvas.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/collide_box.o : collide_box.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/input.o : input.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/line.o : line.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/matrix.o : matrix.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/mesh.o : mesh.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/object.o : object.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/plane.o : plane.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/segment.o : segment.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/transform.o : transform.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/triangle.o : triangle.c
	@$(CC) $(CFLAGS) -c $^ -o $@

../$(OBJ_DIR)/op_engine/vector.o : vector.c
	@$(CC) $(CFLAGS) -c $^ -o $@